---
 - name: loop
   hosts: all
   become: true
   tasks:
   - name: installing packages
     ansible.builtin.apt:
       name: tomcat
       state: latest

   - name: startng packages
     ansible.builtin.apt:
       name: tomcat
       state: fixed
...
