---
- name: playbook new
  hosts: all
  vars:
   a: "This is first task"
   b: "This is Second task"
  tasks:
   - name: task-1
     debug:
      msg: "{{a}}"
   - name: task-2
     debug:
      msg: "{{b}}"
...

